package constants;

public enum PieceEnum {
    EMPTY,
    LION_PLAYER,
    LION_ENEMY,
    ELEPHANT_PLAYER,
    ELEPHANT_ENEMY,
    GIRAFFE_PLAYER,
    GIRAFFE_ENEMY,
    CHICK_PLAYER,
    CHICK_ENEMY,
    CHICKEN_PLAYER,
    CHICKEN_ENEMY,
}
